SAMPLE_TRANSCRIPT = [
  "where is princess",
  "what is that",
  "so we can beep it so it can spin",
  "so it can do this",
  "spin it",
  "where is the blanket",
  "no",
  "oh food",
  "my pillow",
  "where is blanket",
  "what do you want to eat",
  "then maybe you shoud've cook it",
  "bring it in the oven",
  "we need plate",
  "where's pizza plate",
  "we got to time it",
  "where's the timer",
  "maybe I could time",
  "can I do it",
  "where is it",
  "does it open",
  "can I cook it",
  "yes",
  "so you can eat it",
  "maybe it",
  "I can do it",
  "can we call somebody",
  "how you take pictures",
  "do movie",
  "what is it",
  "I can see it",
  "we going to put it",
  "I can put it",
  "put it in here",
  "why",
  "is that you",
  "who is this",
  "my friend",
  "is this song",
  "will it come on",
  "can you turn it",
  "can i turn it up",
  "bobblehead",
  "then go",
  "i don't want to go",
  "i want play with you",
  "where you going",
  "i want play with that",
  "i want play with that ball",
  "we can put in this"
]